@ZonaVermelha.API_HostAddress = http://localhost:5083

### 1. Criar usuário
POST {{ZonaVermelha.API_HostAddress}}/api/usuarios
Content-Type: application/json

{
  "nome": "Guilherme",
  "email": "guilherme@email.com"
}

###

### 2. Criar relato (usar o id retornado no passo 1)
POST {{ZonaVermelha.API_HostAddress}}/api/relatos
Content-Type: application/json

{
  "descricao": "Assalto a mão armada, homem de camisa vermelha",
  "latitude": -20.2900,
  "longitude": -40.2925,
  "usuarioId": "SEU-USUARIO-ID-AQUI"
}

###

### 3. Segundo relato próximo (deve agrupar na mesma zona)
POST {{ZonaVermelha.API_HostAddress}}/api/relatos
Content-Type: application/json

{
  "descricao": "Roubo de celular, suspeito fugiu correndo",
  "latitude": -20.2905,
  "longitude": -40.2925,
  "usuarioId": "SEU-USUARIO-ID-AQUI"
}

### Buscar zonas próximas
GET {{ZonaVermelha.API_HostAddress}}/api/zonas?latitude=-20.2900&longitude=-40.2925


### Teste 1: Descrição vazia (deve retornar 400)
POST {{ZonaVermelha.API_HostAddress}}/api/relatos
Content-Type: application/json

{
  "descricao": "",
  "latitude": -20.2900,
  "longitude": -40.2925,
  "usuarioId": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
}

###

### Teste 2: Usuário inexistente (deve retornar 404)
POST {{ZonaVermelha.API_HostAddress}}/api/relatos
Content-Type: application/json

{
  "descricao": "Assalto",
  "latitude": -20.2900,
  "longitude": -40.2925,
  "usuarioId": "00000000-0000-0000-0000-000000000001"
}