// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZonaVermelha.Infrastructure;

#nullable disable

namespace ZonaVermelha.Infrastructure.Migrations
{
    [DbContext(typeof(ZonaVermelhaDbContext))]
    partial class ZonaVermelhaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("ZonaVermelha.Domain.Relato", b =>
                {
                    b.Property<Guid>("IdRelato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ZonaId")
                        .HasColumnType("TEXT");

                    b.HasKey("IdRelato");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("ZonaId");

                    b.ToTable("Relatos");
                });

            modelBuilder.Entity("ZonaVermelha.Domain.Usuario", b =>
                {
                    b.Property<Guid>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdUsuario");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ZonaVermelha.Domain.Zona", b =>
                {
                    b.Property<Guid>("IdZona")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadaEm")
                        .HasColumnType("TEXT");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<int>("NivelIntensidadeZona")
                        .HasColumnType("INTEGER");

                    b.Property<double>("RaioMetros")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("UltimaAtividade")
                        .HasColumnType("TEXT");

                    b.HasKey("IdZona");

                    b.ToTable("Zonas");
                });

            modelBuilder.Entity("ZonaVermelha.Domain.Relato", b =>
                {
                    b.HasOne("ZonaVermelha.Domain.Usuario", null)
                        .WithMany("Relatos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZonaVermelha.Domain.Zona", "Zona")
                        .WithMany("RelatosZona")
                        .HasForeignKey("ZonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Zona");
                });

            modelBuilder.Entity("ZonaVermelha.Domain.Usuario", b =>
                {
                    b.Navigation("Relatos");
                });

            modelBuilder.Entity("ZonaVermelha.Domain.Zona", b =>
                {
                    b.Navigation("RelatosZona");
                });
#pragma warning restore 612, 618
        }
    }
}
